### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by masone**
Requested in #1

Adds bower.json to the repository as described in http://bower.io/docs/creating-packages. Still needs to be registered, see http://bower.io/docs/creating-packages/#register

This is my first bower package definition, so please review thoroughly. Process does not seem to be too complex though and installation via github worked for me.

### CODE REVIEW

**Comment by LoicMahieu** [comment]
bower.json looks fine.
It is critical for many team to publish this package on package managers and keep a clean versioning (git tags!).
Is there anyone to maintain the project?

**Comment by LoicMahieu** [comment]
Having `bower.json` in source is not enough. You need to publish it to bower: http://bower.io/docs/creating-packages/

Unfortunately I see that someone has already taken the package name `js-marker-clusterer`... 
https://github.com/Haixing-Hu/js-marker-clusterer owned by @Haixing-Hu

**Comment by Haixing-Hu** [comment]
Yes，I have forked this repository, added a bower configuration file, and registered it to the bower registry for my personal use.

My fork is exactly the same as the original one, and I will keep it synchronized as much as possible.

If anybody think it should be changed to point to the original repository, I would like to unregister it.

But please give me sometime to do that, because the Chinese GFW blocked bower registry recently. I don't know why the fucking GFW blocks so many technical websites :-(  All my previous jumping wall methods, including VPN, Shadowsocks, ssh, etc, were disabled by the recent upgrading of the GFW.  I'm still finding a way to jump the wall.

**Comment by broady** [comment]
OK, thanks, @Haixing-Hu. Update this thread when you have access again :)

Cheers

**Comment by masone** [comment]
@Haixing-Hu ping

**Comment by zendre4** [comment]
+1

**Comment by Haixing-Hu** [comment]
Hi, I tried to unregister the package, but got the following error:

```
starfish@Starfishs-iMac:js-marker-clusterer$bower login -t xxxxxxxx(my github token)
bower EAUTH         Logged in as starfish
starfish@Starfishs-iMac:js-marker-clusterer$bower unregister js-marker-clusterer
? You are about to remove component "js-marker-clusterer" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are depending on. Are you really sure? Yes
bower unregister    js-marker-clusterer
bower EFORBIDDEN    Must have push access to view repository collaborators.
```

I have spent half an hour to google the answer, without any result :-( 

Could anybody help me? @masone

**Pull request merged**
