### PR TITLE
Marker cluster images URLs updated

### LINKED ISSUE #54: Icons gone?!
The default cluster-icon is suddenly gone?

### PR DESCRIPTION
**Pull request by davidpelayo**
Fixes #54 and #59, at least what urls are used on this repo.

This doesn't fix those apps with the SVN based codebase which still point to the old repo, due resources aren't available (they have removed them out).

### CODE REVIEW

**Comment by davidpelayo** [comment]
Related to #56, #57 and #60.

**Comment by davidpelayo** [comment]
@WACMemphis I've updated the url to: 

``` javascript
MarkerClusterer.prototype.MARKER_CLUSTER_IMAGE_PATH_ =
    'https://googlemaps.github.io/js-marker-clusterer/' +
    'images/m';
```

**Comment by AlaorSilva** [comment]
The only URL that works for me on markerclusterer_compiled.js and markerclusterer.js is
https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m

Neither CDN or https://googlemaps.github.io/js-marker-clusterer/ works for me.

When I put one of above the map goes to somewhere else, and I have no markers

**Comment by ghost** [comment]
@AlaorSilva 
Works perfectly fine with CDN here. Make sure all of them end with "images/m"

**Comment by PeterTheOne** [comment]
fixed by 2f659a3

**Pull request closed without merging**
