### PR TITLE
Changed HTTP to HTTPS in image link

### PR DESCRIPTION
**Pull request by justinkwanlee**
I changed the url for the images to HTTPS, otherwise the browsers will throw an error saying that there are unencrpyted items (for sites that are using HTTPS)

### CODE REVIEW

**Comment by justinkwanlee** [comment]
@googlebot I Signed it!

**Comment by buren** [comment]
+1, please merge

**Comment by Tastaturberuf** [comment]
:+1:

**Comment by XmlmXmlmX** [comment]
+1

**Comment by Tomtomgo** [comment]
I think it would be better to use '**//**google-maps-utility-library-v3.googlecode.com/sv...' instead of hard-coding https with '**https://**google-maps-utility-library-v3.googlecode.com/sv...'. This way it will not mix http/https.

**Comment by buren** [comment]
@Tomtomgo what is the harm in loading that over HTTPS even though the page is server over HTTP?

**Comment by Tomtomgo** [comment]
Instead of forcing HTTP it will now force HTTPS. It's just not necessary.

**Comment by buren** [comment]
@Tomtomgo sure, I don't see any harm in doing that, just was curious if there was any particular reason :)

**Pull request merged**
